name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884
            - run: uv sync --locked
            - run: uv run pytest